##Numpy array and basics
learn about numpy

In [6]:
import numpy as np

### creating array from list


In [7]:
arr_1d=np.array([1,2,3,4,5])
print("1d array:",arr_1d)

arr_2d=np.array([[1,2,3],[1,2,3]])
print("2d array:",arr_2d)


1d array: [1 2 3 4 5]
2d array: [[1 2 3]
 [1 2 3]]


### List vs numpy


In [8]:
py_list=[1,2,3]
print("python list multiplication",py_list*2)
np_array=np.array([1,2,3])
print("python list multiplication",np_array*2)


python list multiplication [1, 2, 3, 1, 2, 3]
python list multiplication [2 4 6]


In [9]:
import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("\n List operation time:",time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print("\n numpy operation time:",time.time()-start)




 List operation time: 0.009533882141113281

 numpy operation time: 0.0050160884857177734


### creating array from scratch


In [13]:
zeros=np.zeros((3,4))
print("zero array:",zeros)

ones=np.ones((4,4))
print("ones array",ones)

full=np.full((2,2),7)
print("full array:\n", full)

random=np.random.random((2,3))
print("random :\n",random)

sequence=np.arange(0,10,2)
print("sequence:\n",sequence)

zero array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random :
 [[0.2423782  0.18491504 0.7059516 ]
 [0.988289   0.90999877 0.52201543]]
sequence:
 [0 2 4 6 8]


### vector ,matrix and tensor


In [14]:
vector=np.array([1,2,3])
print("vector:",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("matrix:\n",matrix)

tensor=np.array([[[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]]])
print("tensor:\n",tensor)

vector: [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
tensor:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### array properties

In [15]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape of array",arr.shape)
print("dimension of array",arr.ndim)
print("size of array",arr.size)
print("Dtype of array",arr.dtype)




shape of array (2, 3)
dimension of array 2
size of array 6
Dtype of array int64


### array reshaping

In [ ]:
arr=np.arange(12)
print("original array:\n",arr)

reshaped=arr.reshape((3,4))
print("reshaped array:\n",reshaped)

flattend=reshaped.flatten()
print("flatten array:\n",flattend)

#ravel(returns view, instead of copy)
raveled=reshaped.ravel()
print("ravel array:\n",raveled)

#tranpose
transposed=raveled.T()
print("transpose array:\n",transposed)






original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
