## Numpy array operation

In [6]:
import numpy as np


In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing :",arr[2:7])
print("with step",arr[1:8:2])
print("negative indexing",arr[-3])#last se third value

basic slicing : [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 7


In [9]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("specific element:",arr_2d[1,2]) #index not position[row,col]
print("enrire row :",arr_2d[1])
print("entire col :",arr_2d[:,1])

specific element: 6
enrire row : [4 5 6]
entire col : [2 5 8]


## Sorting

In [ ]:
unsorted=np.array([1,4,2,5,1,3,9,4,2])
print("sorted array:",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[5,2],[2,4]])
print("sorted 2d_array by row:",np.sort(arr_2d_unsorted,axis=0)) # top to bottom
print("sorted 2d_array:",np.sort(arr_2d_unsorted,axis=1))#left to right


sorted array: [1 1 2 2 3 4 4 5 9]
sorted 2d_array by row: [[2 1]
 [3 2]
 [5 4]]
sorted 2d_array: [[1 3]
 [2 5]
 [2 4]]


## filter

In [16]:
number=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=number[number%2==0]
print("evens numbers:",even_number)

evens numbers: [ 2  4  6  8 10]


## filter with mask

In [ ]:
mask=number>5 ## we store expresion in mask
print("numbers greater than 5:",number[mask]) 

numbers greater than 5 [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [18]:
indices=[0,2,4]
print("idices:",number[indices])

where_result=np.where(number>5)
print("where number greater than 5:",number[where_result])

idices: [1 3 5]
where number greater than 5: [ 6  7  8  9 10]


In [ ]:
condition_array=np.where(number>5,number*2,number) # (condtion x,y)
print("condition_array: ",condition_array)

condition_array:  [ 1  2  3  4  5 12 14 16 18 20]


## for example
 if(number>5){
    number*2
 }else{
   number
 }

### Adding and removing data

In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### array compatiblity

In [28]:
arrA1=np.array([1,2,3])
arrA2=np.array([4,5,6])
arrA3=np.array([7,8,9])
print("compatibility shapes: ",arrA1.shape== arrA2.shape)

compatibility shapes:  True


In [30]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
with_new_row=np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(original)
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [31]:
arr=np.array([1,2,3,4,5,6])
deleted=np.delete(arr,2)
print("array after deletion:",deleted)

array after deletion: [1 2 4 5 6]
